<?php

/**
 * @file
 * Primary module hooks for spotify module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function spotify_theme($existing, $type, $theme, $path) {
    return array(
        'launch' => array( 
        	'template' => 'launch',
            'variables' => array(
            	'launch' => NULL,
            ),
        ),
        'artist' => array( 
            'template' => 'artist',
            'variables' => array(
                'id' => NULL,
                'artist' => NULL,
                'tracks' => NULL,
            ),
        ),
    );
}
